const productos = [
  {
    id: 1,
    nombre: "Laptop Gaming MSI",
    precio: 1299,
    precioOriginal: null,
    categoria: "Portátiles",
    stock: 8,
    enOferta: false,
  },
  {
    id: 2,
    nombre: 'Monitor LG 27"',
    precio: 249,
    precioOriginal: 299,
    categoria: "Monitores",
    stock: 15,
    enOferta: true,
  },
  {
    id: 3,
    nombre: "Teclado Mecánico Corsair",
    precio: 189,
    precioOriginal: null,
    categoria: "Periféricos",
    stock: 22,
    enOferta: false,
  },
  {
    id: 4,
    nombre: "Mouse Logitech Pro",
    precio: 99,
    precioOriginal: 129,
    categoria: "Periféricos",
    stock: 0,
    enOferta: true,
  },
  {
    id: 5,
    nombre: "Auriculares Sony Noise Cancelling",
    precio: 550,
    precioOriginal: 500,
    categoria: "Audio",
    stock: 5,
    enOferta: true,
  },
  {
    id: 6,
    nombre: "Webcam HD 1080p",
    precio: 79,
    precioOriginal: null,
    categoria: "Accesorios",
    stock: 12,
    enOferta: false,
  },
  {
    id: 7,
    nombre: "SSD Samsung 1TB",
    precio: 119,
    precioOriginal: 149,
    categoria: "Almacenamiento",
    stock: 30,
    enOferta: true,
  },
  {
    id: 8,
    nombre: "Router WiFi 6",
    precio: 199,
    precioOriginal: null,
    categoria: "Redes",
    stock: 7,
    enOferta: false,
  },
  {
    id: 9,
    nombre: "Mousepad Extenso",
    precio: 49,
    precioOriginal: 69,
    categoria: "Periféricos",
    stock: 40,
    enOferta: true,
  },
  {
    id: 10,
    nombre: "Hub USB-C 7 Puertos",
    precio: 89,
    precioOriginal: null,
    categoria: "Accesorios",
    stock: 18,
    enOferta: false,
  },
]
